---
ID: "3ba0a2bb-19bb-45cc-b9c3-dc8858df1aa4"
Parent: "8d67073e-0795-4398-a183-e140d63f6324"
Template: "8d67073e-0795-4398-a183-e140d63f6324"
Path: /sitecore/templates/Feature/SXA Tutorial/Text Teaser/Data Source/Text Teaser Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4EE36CDB-DFC2-40DA-8CAC-563C035F2778}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240204T164509Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cb71c44e-5ec3-471f-abc6-98850967c5a5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240204T164525Z
